/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stddef.h>
#include <isa-l.h>
#include <dlfcn.h>
#include <jni.h>
#include <assert.h>

#ifndef ORG_APACHE_ORC_ISAL_CODEC
#define ORG_APACHE_ORC_ISAL_CODEC
#ifdef __cplusplus

extern "C" {
#endif

/* A helper macro to 'throw' a java exception. */
#define THROW(env, exception_name, message) \
  { \
	jclass ecls = (*env)->FindClass(env, exception_name); \
	if (ecls) { \
	  (*env)->ThrowNew(env, ecls, message); \
	  (*env)->DeleteLocalRef(env, ecls); \
	} \
  }

/* A helper macro to convert the java 'stream-handle' to a z_stream pointer. */
#define ZSTREAM(stream) ((struct isal_zstream *)((ptrdiff_t)(stream)))
#define ZSTATE(state) ((struct inflate_state *)((ptrdiff_t)(state)))
/* A helper macro to convert the z_stream pointer to the java 'stream-handle'. */
#define JLONG(stream) ((jlong)((ptrdiff_t)(stream)))

/*
 * Class:     Java_org_apache_orc_impl_IsalCodec
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_orc_impl_IsalCodec_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     Java_org_apache_orc_impl_IsalCodec
 * Method:    deflateinit
 * Signature: (II[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_orc_impl_IsalCodec_deflateinit
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     Java_org_apache_orc_impl_IsalCodec
 * Method:    inflateinit
 * Signature: (II[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_orc_impl_IsalCodec_inflateinit
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_apache_hadoop_hive_ql_io_orc_IzlibCodec
 * Method:    deflate
 * Signature: (JI[BII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hive_ql_io_orc_IzlibCodec_deflate
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     Java_org_apache_orc_impl_IsalCodec
 * Method:    inflate
 * Signature: (JI[BII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_orc_impl_IsalCodec_inflate
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     Java_org_apache_orc_impl_IsalCodec
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_orc_impl_IsalCodec_end
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
