name: clang-format

on:
  push:
    paths-ignore:
    - 'docker'
    - 'examples'
    - 'java'
    - 'proto'
    - 'site/**'
    branches:
    - main
  pull_request:
    paths-ignore:
    - 'docker'
    - 'examples'
    - 'java'
    - 'proto'
    - 'site/**'
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'c++'
          - 'tools'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C++ code
      uses: jidicula/clang-format-action@v4.2.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
