name: Daily (main)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-build-and-test:
    if: github.repository == 'apache/orc'
    uses: ./.github/workflows/build_and_test.yml
